apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-app
  namespace: payment-app
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - payment.apps.local
      secretName: apps-local-tls
  rules:
    - host: payment.apps.local
      http:
        paths: 
        - path: /
          pathType: Prefix
          backend:
            service:
              name: payment-app
              port:
                number: 80