apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-app
  namespace: token-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: token-app
  template:
    metadata:
      labels:
        app: token-app
    spec:
      containers:
        - name: token-app
          image: hashicorp/http-echo:latest
          args:
            - "-text=Hello from token-app!"
            - "-listen=:8080"
          ports:
            - containerPort: 8080